data:
  cost:
    base: 5000.0
    capital: 10
    cruiser: 25
    frigate: 10
  effect: '<p>Can land: frigates and fighters only.</p>'
  mass:
    base: 1.0
    capital: 4
    cruiser: 3
    frigate: 2
  min_class: fighter
  name: Atmospheric configuration
  power:
    base: 0.0
    capital: 1
    cruiser: 1
    frigate: 1
